<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VIIDII</AssemblyName>
    <InvariantGlobalization>false</InvariantGlobalization>
    <NoWarn>$(NoWarn);CS8602;CS8603;CS8604;CS8618;CS8619;CS8629;CS8714</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="figma\**" />
    <Content Remove="figma\**" />
    <EmbeddedResource Remove="figma\**" />
    <None Remove="figma\**" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
